1. Write a Python Program to Add Two Matrices?

In [6]:
import numpy as np

matrix1 = np.array([[1,2,3,4,5],
                   [4,53,2,4,7],
                   [5,4,3,2,8]])
matrix2 = np.array([[9,8,6,5,4],
                  [5,4,3,21,3],
                  [9,7,4,32,1]])
Adding_matrix = np.add(matrix1, matrix2)
print("The Sum of two matrix    \n\n{}  and \n\n{}  is \n\n{} ".format(matrix1,matrix2,Adding_matrix))

[[10 10  9  9  9]
 [ 9 57  5 25 10]
 [14 11  7 34  9]]
The Sum of two matrix 

[[ 1  2  3  4  5]
 [ 4 53  2  4  7]
 [ 5  4  3  2  8]]  and 

[[ 9  8  6  5  4]
 [ 5  4  3 21  3]
 [ 9  7  4 32  1]]  is 

[[10 10  9  9  9]
 [ 9 57  5 25 10]
 [14 11  7 34  9]] 


2. Write a Python Program to Multiply Two Matrices?

In [7]:
import numpy as np

matrix1 = np.array([[13,42,64],
        [3,7,4],
        [9,1,2]])
matrix2 = np.array([[2,4,7],
        [55,67,8],
        [8,9,1]])

mulMat = np.dot(matrix1,matrix2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(matrix1,matrix1,mulMat))

The product of two matrix 

[[13 42 64]
 [ 3  7  4]
 [ 9  1  2]]  and 

[[13 42 64]
 [ 3  7  4]
 [ 9  1  2]]  is 

[[2848 3442  491]
 [ 423  517   81]
 [  89  121   73]] 


3. Write a Python Program to Transpose a Matrix?

In [2]:
def Matrix(n,v=0):
    M=[]             
    for i in range(n):
        
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def crMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def prMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 

def tpMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = crMatrix(n)

print("Display Array M1 In Matrix Form")
prMatrix(M1,n)

result = Matrix(n)
result = tpMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 3
Enter the element :
1
2
3
4
5
6
7
8
9
Display Array M1 In Matrix Form
1 2 3 
4 5 6 
7 8 9 
Transposed Matrix
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [6]:
Arr = input("Enter string:  ")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string:  I LOVE TO CODE
CODE
I
LOVE
TO


5. Write a Python Program to Remove Punctuation From a String?

In [10]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuationsSun rise in the east!@#%&^(*)(_)*&%$#!@$%^&
Sun rise in the east
